workflows:
  le-livreur-pro-android:
    name: Le Livreur Pro - Android (Physical Device)
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "ci.lelivreurpro.le_livreur_pro"
        BUILD_APP_NAME: "Le Livreur Pro"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK for physical device
        script: |
          flutter build apk \
            --debug \
            --dart-define=ENVIRONMENT=development \
            --dart-define=SUPABASE_URL=$SUPABASE_URL \
            --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
      - name: Show build results
        script: |
          echo "=== Build completed successfully! ==="
          echo "APK location: build/app/outputs/flutter-apk/app-debug.apk"
          ls -la build/app/outputs/flutter-apk/
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/flutter-apk/mapping.txt

# Global environment variables
environment:
  vars:
    ENVIRONMENT: "development"
    FLUTTER_VERSION: "3.32.8"
    DART_VERSION: "3.8.1"
  flutter: stable
  cache:
    flutter_pub: true
    gradle: true

# Trigger conditions
triggering:
  events:
    - push
    - pull_request
  branch_patterns:
    - pattern: "main"
      include: true
      source: true
    - pattern: "develop"
      include: true
      source: true

# Build timeout
build_timeout: 30
max_build_duration: 30
